# Generated by Django 4.2.4 on 2023-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('type_identifiant', models.CharField(choices=[('CIN', 'CIN'), ('Carte Sejour', 'Carte Sejour'), ('Passeport', 'Passeport')], default='typeIdentifiant', max_length=100)),
                ('identifiant', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('gouvernorat', models.CharField(choices=[('Gouvernorat', 'Gouvernorat'), ('ARIANA', 'ARIANA'), ('BEJA', 'BEJA'), ('BEN AROUS', 'BEN AROUS'), ('BIZERTE', 'BIZERTE'), ('GABES', 'GABES'), ('GAFSA', 'GAFSA'), ('JENDOUBA', 'JENDOUBA'), ('KAIROUAN', 'KAIROUAN'), ('KASSERINE', 'KASSERINE'), ('KEBILI', 'KEBILI'), ('KEF', 'KEF'), ('MAHDIA', 'MAHDIA'), ('MANOUBA', 'MANOUBA'), ('MEDENINE', 'MEDENINE'), ('MONASTIR', 'MONASTIR'), ('NABEUL', 'NABEUL'), ('SFAX', 'SFAX'), ('SIDI BOUZID', 'SIDI BOUZID'), ('SILIANA', 'SILIANA'), ('SOUSSE', 'SOUSSE'), ('TATAOUINE', 'TATAOUINE'), ('TOZEUR', 'TOZEUR'), ('TUNIS', 'TUNIS'), ('ZAGHOUAN', 'ZAGHOUAN')], default='Gouvernorat', max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('gsm_client', models.CharField(max_length=20)),
                ('deja_client', models.BooleanField(default=False)),
                ('code_client_existant', models.CharField(blank=True, max_length=100, null=True)),
                ('cin_client_existant', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_proprietaire_ligne', models.CharField(max_length=100)),
                ('numero_appel', models.CharField(max_length=100)),
                ('produit', models.CharField(choices=[('UNO VDSL 20M', 'UNO VDSL 20M'), ('UNO VDSL 30M', 'UNO VDSL 30M'), ('UNO VDSL 50M', 'UNO VDSL 50M'), ('UNO VDSL 100M', 'UNO VDSL 100M')], max_length=100, null=True)),
                ('paiement', models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Annuel', 'Annuel')], max_length=100, null=True)),
                ('recuperer_modem', models.CharField(max_length=100)),
                ('agence', models.CharField(choices=[('Agence Ariana', 'Agence Ariana'), ('Agence Av. de la République', 'Agence Av. de la République'), ('Agence El Menzah', 'Agence El Menzah'), ('Agence Ennasr', 'Agence Ennasr'), ('Agence Kheireddine Pacha', 'Agence Kheireddine Pacha'), ('Agence Lac 1', 'Agence Lac 1'), ('Agence Lac 2', 'Agence Lac 2'), ('Agence Nabeul', 'Agence Nabeul'), ('Agence Sousse', 'Agence Sousse'), ('Agence Tunis Belvédère', 'Agence Tunis Belvédère'), ('Agence Tunis Centre Ville', 'Agence Tunis Centre Ville'), ('Agence Tunis El Menzah 9', 'Agence Tunis El Menzah 9'), ('Agence Tunis Lafayette', 'Agence Tunis Lafayette'), ('Agence Tunis Lac', 'Agence Tunis Lac'), ('Agence Tunis Le Kram', 'Agence Tunis Le Kram'), ('Agence Tunis Les Berges du Lac', 'Agence Tunis Les Berges du Lac'), ('Agence Tunis Médina', 'Agence Tunis Médina'), ('Agence Tunis Montplaisir', 'Agence Tunis Montplaisir'), ('Agence Tunis Mutuelle Ville', 'Agence Tunis Mutuelle Ville'), ('Agence Tunis Route de la Marsa', 'Agence Tunis Route de la Marsa'), ('Agence Tunis Zone Industrielle', 'Agence Tunis Zone Industrielle')], max_length=100, null=True)),
                ('total_a_payer', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=100, verbose_name='Horaire')),
                ('gouvernorat', models.CharField(choices=[('Gouvernorat', 'Gouvernorat'), ('ARIANA', 'ARIANA'), ('BEJA', 'BEJA'), ('BEN AROUS', 'BEN AROUS'), ('BIZERTE', 'BIZERTE'), ('GABES', 'GABES'), ('GAFSA', 'GAFSA'), ('JENDOUBA', 'JENDOUBA'), ('KAIROUAN', 'KAIROUAN'), ('KASSERINE', 'KASSERINE'), ('KEBILI', 'KEBILI'), ('KEF', 'KEF'), ('MAHDIA', 'MAHDIA'), ('MANOUBA', 'MANOUBA'), ('MEDENINE', 'MEDENINE'), ('MONASTIR', 'MONASTIR'), ('NABEUL', 'NABEUL'), ('SFAX', 'SFAX'), ('SIDI BOUZID', 'SIDI BOUZID'), ('SILIANA', 'SILIANA'), ('SOUSSE', 'SOUSSE'), ('TATAOUINE', 'TATAOUINE'), ('TOZEUR', 'TOZEUR'), ('TUNIS', 'TUNIS'), ('ZAGHOUAN', 'ZAGHOUAN')], default='Gouvernorat', max_length=100)),
                ('localite', models.CharField(choices=[('Localité', 'Localité'), ('ARIANA', 'ARIANA'), ('BORJ LOUZIR', 'BORJ LOUZIR'), ('CITE ETTADAMAN', 'CITE ETTADAMAN'), ('EL MENZAH 6', 'EL MENZAH 6'), ('ENNASR', 'ENNASR'), ('NKHILET', 'NKHILET')], default='Localité', max_length=100)),
                ('type', models.CharField(choices=[('Type', 'Type'), ('Agence', 'Agence'), ('Revendeur', 'Revendeur')], default='Type', max_length=100)),
                ('popup_name', models.CharField(max_length=100)),
            ],
        ),
    ]
