# Generated by Django 4.2.4 on 2023-08-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_appel',
            field=models.CharField(max_length=10),
        ),
    ]
