# Generated by Django 4.2.4 on 2023-08-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_client_captcha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_existing_customer',
            new_name='deja_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lon',
        ),
        migrations.AddField(
            model_name='client',
            name='email_client',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='agence',
            field=models.CharField(choices=[('Agence Ariana', 'Agence Ariana'), ('Agence Av. de la République', 'Agence Av. de la République'), ('Agence El Menzah', 'Agence El Menzah'), ('Agence Ennasr', 'Agence Ennasr'), ('Agence Kheireddine Pacha', 'Agence Kheireddine Pacha'), ('Agence Lac 1', 'Agence Lac 1'), ('Agence Lac 2', 'Agence Lac 2'), ('Agence Nabeul', 'Agence Nabeul'), ('Agence Sousse', 'Agence Sousse'), ('Agence Tunis Belvédère', 'Agence Tunis Belvédère'), ('Agence Tunis Centre Ville', 'Agence Tunis Centre Ville'), ('Agence Tunis El Menzah 9', 'Agence Tunis El Menzah 9'), ('Agence Tunis Lafayette', 'Agence Tunis Lafayette'), ('Agence Tunis Lac', 'Agence Tunis Lac'), ('Agence Tunis Le Kram', 'Agence Tunis Le Kram'), ('Agence Tunis Les Berges du Lac', 'Agence Tunis Les Berges du Lac'), ('Agence Tunis Médina', 'Agence Tunis Médina'), ('Agence Tunis Montplaisir', 'Agence Tunis Montplaisir'), ('Agence Tunis Mutuelle Ville', 'Agence Tunis Mutuelle Ville'), ('Agence Tunis Route de la Marsa', 'Agence Tunis Route de la Marsa'), ('Agence Tunis Zone Industrielle', 'Agence Tunis Zone Industrielle')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cin_client_existant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_client_existant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='gouvernorat',
            field=models.CharField(choices=[('Gouvernorat', 'Gouvernorat'), ('ARIANA', 'ARIANA'), ('BEJA', 'BEJA'), ('BEN AROUS', 'BEN AROUS'), ('BIZERTE', 'BIZERTE'), ('GABES', 'GABES'), ('GAFSA', 'GAFSA'), ('JENDOUBA', 'JENDOUBA'), ('KAIROUAN', 'KAIROUAN'), ('KASSERINE', 'KASSERINE'), ('KEBILI', 'KEBILI'), ('KEF', 'KEF'), ('MAHDIA', 'MAHDIA'), ('MANOUBA', 'MANOUBA'), ('MEDENINE', 'MEDENINE'), ('MONASTIR', 'MONASTIR'), ('NABEUL', 'NABEUL'), ('SFAX', 'SFAX'), ('SIDI BOUZID', 'SIDI BOUZID'), ('SILIANA', 'SILIANA'), ('SOUSSE', 'SOUSSE'), ('TATAOUINE', 'TATAOUINE'), ('TOZEUR', 'TOZEUR'), ('TUNIS', 'TUNIS'), ('ZAGHOUAN', 'ZAGHOUAN')], default='Gouvernorat', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='gsm_client',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='identifiant',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_client',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_proprietaire_ligne',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_appel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='paiement',
            field=models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Annuel', 'Annuel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='produit',
            field=models.CharField(choices=[('UNO VDSL 20M', 'UNO VDSL 20M'), ('UNO VDSL 30M', 'UNO VDSL 30M'), ('UNO VDSL 50M', 'UNO VDSL 50M'), ('UNO VDSL 100M', 'UNO VDSL 100M')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='recuperer_modem',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='total_a_payer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_identifiant',
            field=models.CharField(choices=[('CIN', 'CIN'), ('Carte Sejour', 'Carte Sejour'), ('Passeport', 'Passeport')], default='typeIdentifiant', max_length=100),
        ),
    ]
